#!/bin/sh

echo $#

if [[ $# -ne 1 ]]; then
	echo 'give me something'
	exit
fi

rm --force log
./man2html5.py "/usr/share/man/man1/${1}.1.gz"
gvim log
gvim "/usr/share/man/man1/${1}.1.gz"
gvim ./result.html
urxvt -e zsh -c "source ~/.zshrc && man ${1}" &
firefox -new-window ./result.html &>/dev/null
