#!/bin/sh

if [[ $# -ne 1 ]]; then
	echo 'give me something'
	exit
fi

rm --force log
./hitman.py "./pages/${1}"

if [[ $? -ne 0 ]]; then
	exit
fi

gvim log
gvim "./pages/${1}"
gvim ./result.html
urxvt -e zsh -c "source ~/.zshrc && man ./pages/${1}" &
firefox -new-tab ./result.html &>/dev/null
